# Generated by Django 3.2.14 on 2022-07-06 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('image', models.FileField(upload_to='studentapp/images')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stateview', to='studentapp.state')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districtview', to='studentapp.state'),
        ),
    ]
