# Generated by Django 3.2.14 on 2022-07-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
