# Generated by Django 3.2.14 on 2022-07-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_remove_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.FileField(default=None, upload_to='studentapp/images/'),
            preserve_default=False,
        ),
    ]
